"""Seed alignment

Revision ID: c89ae72f326c
Revises: 
Create Date: 2026-03-18 04:30:24.828683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c89ae72f326c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='statusenum'), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_index(op.f('ix_category_category_name'), 'category', ['category_name'], unique=True)
    op.create_table('role',
    sa.Column('role_name', sa.Enum('SuperAdmin', 'Manager', 'Staff', name='roleroleenum'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='statusenum'), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('store',
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='statusenum'), nullable=False),
    sa.Column('id_store', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_store')
    )
    op.create_index(op.f('ix_store_store_name'), 'store', ['store_name'], unique=True)
    op.create_table('employee',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='statusenum'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id_role'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id_store'], ),
    sa.PrimaryKeyConstraint('id_employee')
    )
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    op.create_table('product_template',
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fixed_selling_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='statusenum'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id_category'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_index(op.f('ix_product_template_sku'), 'product_template', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_template_sku'), table_name='product_template')
    op.drop_table('product_template')
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_store_store_name'), table_name='store')
    op.drop_table('store')
    op.drop_table('role')
    op.drop_index(op.f('ix_category_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
