"""
add_stock_sale_sale_item_tables

Revision ID: f0da5d59b7f1
Revises:
Create Date: 2026-05-30 06:24:45.714855

"""

from collections.abc import Sequence

# Identificadores de revisión
revision: str = "f0da5d59b7f1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplicar cambios en el esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir cambios en el esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
